In [1]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 23.0 MB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# run the following chunk to conveniently get the xlsx file ready in lab environment. This code will write the data from the xlsx file to a file named Airport_Data.xlsx, assuming it doesn't exist.

In [ ]:
import requests
import os
if not os.path.isfile("./Airport_Data.xlsx"):
    r = requests.get("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/analysing-spreadsheet-data-with-python/Airport_Data.xlsx")
    f = open("./Airport_Data.xlsx", mode = "wb+")
    f.write(r.content)
    f.close()

In [2]:
import pandas as pd

df_facilities = pd.read_excel("./Airport_Data.xlsx", sheet_name="Facilities")

In [3]:
df_facilities

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
0,50009.*A,AIRPORT,'ADK,3/30/2017,AAL,NONE,AK,ALASKA,ALEUTIANS WEST,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y,PADK,SS-SR
1,50016.1*A,AIRPORT,'AKK,3/30/2017,AAL,NONE,AK,ALASKA,KODIAK ISLAND,AK,...,NACO,00:00:00,NACO,00:00:00,NaN,NaN,NaN,Y,PAKH,NaN
2,50017.*A,AIRPORT,'Z13,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,NaN,SEE RMK
3,50017.1*C,SEAPLANE BASE,'KKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,50020.*A,AIRPORT,'AKI,3/30/2017,AAL,NONE,AK,ALASKA,BETHEL,AK,...,STATE,00:00:00,STATE,00:00:00,NaN,NaN,CARGO,Y-L,PFAK,SS-SR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
746,50920.12*C,SEAPLANE BASE,'2Y3,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,TIE,CARGO,NaN,NaN,NaN
747,50920.*A,AIRPORT,'YAK,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,3RD PARTY SURVEY,00:00:00,3RD PARTY SURVEY,00:00:00,NaN,HGR,CARGO,Y-L,PAYA,SS-SR
748,50925.1*A,AIRPORT,'A77,3/30/2017,AAL,NONE,AK,ALASKA,KUSKOKWIM,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
749,50928.*C,SEAPLANE BASE,'78K,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN
750,50990.*A,AIRPORT,'L20,3/30/2017,AAL,NONE,AK,ALASKA,UPPER YUKON,AK,...,FAA-EST,00:00:00,NaN,NaN,NaN,NaN,CARGO,Y,NaN,NaN

In [4]:
df_facilities["Type"]

0            AIRPORT
1            AIRPORT
2            AIRPORT
3      SEAPLANE BASE
4            AIRPORT
           ...
746    SEAPLANE BASE
747          AIRPORT
748          AIRPORT
749    SEAPLANE BASE
750          AIRPORT
Name: Type, Length: 751, dtype: object

In [6]:
"df_facilities["Type"] == "SEAPLANE_BASE"

SyntaxError: invalid syntax (883318023.py, line 1)

In [11]:
df_facilities["Type"] == "SEAPLANE BASE"

0      False
1      False
2      False
3       True
4      False
       ...
746     True
747    False
748    False
749     True
750    False
Name: Type, Length: 751, dtype: bool

In [12]:
df_facilities.sort_values(by = "ARPElevation", ascending = False)

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
584,50739.1*A,AIRPORT,'AA09,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
630,50738.20*A,AIRPORT,'93AK,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,CARGO,Y,NaN,NaN
265,50324.6*A,AIRPORT,'4Z5,3/30/2017,AAL,NONE,AK,ALASKA,SOUTHEAST FAIRBANKS,AK,...,FAA OE/AAA,00:00:00,FAA OE/AAA,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
582,50738.01*A,AIRPORT,'2AK7,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,50439.18*A,AIRPORT,'AK80,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,50196.3*C,SEAPLANE BASE,'ELV,3/30/2017,AAL,NONE,AK,ALASKA,SKAGWAY-YAKUTAT,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PAEL,NaN
516,50680.*C,SEAPLANE BASE,'A23,3/30/2017,AAL,NONE,AK,ALASKA,WRANGELL-PETERSBURG,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,NaN,NaN,NaN
363,50455.6*C,SEAPLANE BASE,'13Z,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
382,50489.*C,SEAPLANE BASE,'MTM,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,Y,PAMM,NaN
628,50773.5*C,SEAPLANE BASE,'AK62,3/30/2017,AAL,NONE,AK,ALASKA,KETCHIKAN GATEWAY,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,CARGO,N,NaN,NaN

In [14]:
df_facilities.sort_values(by = "ARPElevation", ascending = False).head(n = 5)

,SiteNumber,Type,LocationID,EffectiveDate,Region,DistrictOffice,State,StateName,County,CountyState,...,AirportPositionSource,AirportPositionSourceDate,AirportElevationSource,AirportElevationSourceDate,ContractFuelAvailable,TransientStorage,OtherServices,WindIndicator,IcaoIdentifier,BeaconSchedule2
584,50739.1*A,AIRPORT,'AA09,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
630,50738.20*A,AIRPORT,'93AK,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,CARGO,Y,NaN,NaN
265,50324.6*A,AIRPORT,'4Z5,3/30/2017,AAL,NONE,AK,ALASKA,SOUTHEAST FAIRBANKS,AK,...,FAA OE/AAA,00:00:00,FAA OE/AAA,00:00:00,NaN,NaN,NaN,Y,NaN,NaN
582,50738.01*A,AIRPORT,'2AK7,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,50439.18*A,AIRPORT,'AK80,3/30/2017,AAL,NONE,AK,ALASKA,MATANUSKA-SUSITNA,AK,...,OWNER,00:00:00,OWNER,00:00:00,NaN,NaN,NaN,Y,NaN,NaN

In [15]:
df_facilities["ARPElevation"].max()

3984

In [16]:
df_facilities["ARPElevation"].min()

0

In [17]:
df_seaplane = df_facilities[df_facilities["Type"] == "SEAPLANE BASE"]

In [18]:
df_seaplane.to_excel("./seaplane.xlsx")